# Generated by Django 4.2 on 2024-02-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SetIndexVeldf",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("data", models.DateField()),
                ("vazao", models.DecimalField(decimal_places=3, max_digits=20)),
                ("velocityx", models.DecimalField(decimal_places=3, max_digits=20)),
                ("level", models.DecimalField(decimal_places=3, max_digits=20)),
                (
                    "mean_q_over_a",
                    models.DecimalField(
                        db_column="MeanQoverA", decimal_places=3, max_digits=20
                    ),
                ),
                (
                    "mean_area",
                    models.DecimalField(
                        db_column="MeanArea", decimal_places=3, max_digits=20
                    ),
                ),
            ],
            options={
                "db_table": "setindexveldf",
                "managed": False,
            },
        ),
    ]
