# Generated by Django 4.2.6 on 2023-10-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spd", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parameter",
            name="description",
            field=models.TextField(default="coloque a descrição aqui", max_length=500),
            preserve_default=False,
        ),
    ]
