# Generated by Django 4.2.6 on 2023-10-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spd", "0002_parameter_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="access_station",
            field=models.CharField(default="st00", max_length=10),
            preserve_default=False,
        ),
    ]
